[package]
name = "oxygengine-network"
version = "0.3.5"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2018"
description = "Network module for Oxygen Engine"
license = "MIT"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-network"

[dependencies]
oxygengine-core = { version = "0.3", path = "../oxygengine-core" }
