[package]
name = "oxygengine-network-backend-native"
version = "0.42.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "Network Native backend module for Oxygengine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-network-backend-native"
readme = "../../README.md"

[features]
parallel = ["oxygengine-core/parallel", "oxygengine-network/parallel"]
scalar64 = ["oxygengine-core/scalar64", "oxygengine-network/scalar64"]

[dependencies]
oxygengine-core = { version = "0.42", path = "../core" }
oxygengine-network = { version = "0.42", path = "../network" }
byteorder = "1.3"
