[package]
name = "oxygengine-procedural"
version = "0.21.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "Procedural content generation module for Oxygen Engine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-procedural"
readme = "../README.md"

[features]
parallel = ["rayon"]
scalar64 = ["oxygengine-utils/scalar64"]

[dependencies]
oxygengine-utils = { version = "0.21", path = "../utils" }
psyche-utils = "0.2"
rayon = { version = "1.3", optional = true }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
rand = "0.8"
