[package]
name = "oxygengine-integration-ui-ha"
version = "0.21.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "Integration module of user interface and Hardware Accelerated rendering for Oxygen Engine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-integration-ui-ha"
readme = "../README.md"

[features]
web = [
  "oxygengine-core/web",
  "oxygengine-user-interface/web",
  "oxygengine-ha-renderer/web",
]
parallel = [
  "oxygengine-core/parallel",
  "oxygengine-user-interface/parallel",
  "oxygengine-ha-renderer/parallel",
]
scalar64 = [
  "oxygengine-core/scalar64",
  "oxygengine-user-interface/scalar64",
  "oxygengine-ha-renderer/scalar64",
]

[dependencies]
oxygengine-core = { version = "0.21", path = "../core" }
oxygengine-user-interface = { version = "0.21", path = "../user-interface" }
oxygengine-ha-renderer = { version = "0.21", path = "../ha-renderer" }
raui-tesselate-renderer = { version = "0.38", features = ["index32"] }
serde = { version = "1", features = ["derive"] }
