[package]
name = "oxygengine-backend-desktop"
version = "0.45.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "Desktopeb backend module for Oxygengine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-backend-desktop"
readme = "../../README.md"

[features]
scalar64 = ["oxygengine-core/scalar64"]

[dependencies]
oxygengine-core = { version = "0.45", path = "../core" }
glutin = "0.28"