[package]
name = "oxygengine-ha-renderer"
version = "0.45.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "Hardware Accelerated renderer module for Oxygengine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-ha-renderer"
readme = "../../README.md"

[features]
web = [
  "wasm-bindgen",
  "web-sys",
  "oxygengine-core/web",
  "oxygengine-backend-web",
]
desktop = ["oxygengine-backend-desktop"]
parallel = ["oxygengine-core/parallel"]
scalar64 = ["oxygengine-core/scalar64"]

[dependencies]
oxygengine-core = { version = "0.45", path = "../core" }
oxygengine-animation = { version = "0.45", path = "../animation" }
oxygengine-utils = { version = "0.45", path = "../utils" }
glow = "0.12"
vek = { version = "0.15", features = ["mint", "rgba", "uv"] }
png = "0.17"
jpeg-decoder = "0.3"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.5"
serde_json = "1"
bincode = "1"
ktx2 = "0.3"
tabled = "0.12"
pest = "2.1"
pest_derive = "2.1"
snailquote = "0.3"

[dependencies.wasm-bindgen]
version = "0.2"
optional = true
features = ["serde-serialize"]

[dependencies.oxygengine-backend-web]
version = "0.45"
path = "../backend-web"
optional = true

[dependencies.oxygengine-backend-desktop]
version = "0.45"
path = "../backend-desktop"
optional = true

[dependencies.web-sys]
version = "0.3"
optional = true
features = [
  "WebGl2RenderingContext",
  "Document",
  "HtmlCanvasElement",
  "Window",
  "Element",
  "Event",
]

[profile.dev.package.png]
opt-level = 3

[profile.dev.package.astc-decode]
opt-level = 3
