[package]
name = "oxygengine-ha-renderer"
version = "0.21.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "Hardware Accelerated renderer module for Oxygen Engine"
license-file = "../LICENSE"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-ha-renderer"
readme = "../README.md"

[features]
web = ["wasm-bindgen", "web-sys", "oxygengine-core/web"]
parallel = ["oxygengine-core/parallel"]
scalar64 = ["oxygengine-core/scalar64"]

[dependencies]
oxygengine-core = { version = "0.21", path = "../core" }
glow = "0.11"
vek = { version = "0.15", features = ["mint", "rgba", "uv"] }
png = "0.17"
jpeg-decoder = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = "1"
serde_yaml = "0.8"
wasm-bindgen = { version = "0.2", optional = true, features = ["serde-serialize"] }
ktx2 = "0.2"
pest = "2.1"
pest_derive = "2.1"

[dependencies.web-sys]
version = "0.3"
optional = true
features = [
  'WebGl2RenderingContext',
  'Document',
  'HtmlCanvasElement',
  'Window',
  'Element',
  'Event',
]

[profile.dev.package.png]
opt-level = 3

[profile.dev.package.astc-decode]
opt-level = 3
