[package]
name = "oxygengine-ignite"
version = "0.45.1"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "CLI app used to setup and develop Oxygengine projects"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-ignite"
readme = "../../README.md"

[dependencies]
oxygengine-build-tools = { version = "0.45", path = "../build-tools" }
clap = { version = "4", features = ["derive"] }
cargo_metadata = "0.15"
toml = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = "1"
dirs = "5"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "rustls-tls"] }
chrobry-core = "1"
warp = "0.3"
tokio = { version = "1", features = ["macros"] }
hotwatch = "0.4"
open = "4"
wasm-pack = { version = "0.12", default-features = false }
fs_extra = "1.1"
pathdiff = "0.2"
which = "4.2"
ignore = "0.4"
