[package]
name = "amethyst-integration"
version = "0.1.0"
edition = "2018"

[dependencies]
amethyst = "0.12.0"
log = { version = "0.4.6", features = ["serde"] }
oxygengine-navigation = { path = "../../oxygengine-navigation", version = "0.6" }
winit = "0.19.2"

[features]
default = ["vulkan"]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
nightly = ["amethyst/nightly"]
