[package]
name = "oxygengine-navigation"
version = "0.27.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "Navigation module for Oxygengine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-navigation"
readme = "../../README.md"

[features]
web = ["oxygengine-core/web"]
parallel = ["oxygengine-core/parallel", "navmesh/parallel"]
scalar64 = ["oxygengine-core/scalar64", "navmesh/scalar64"]

[dependencies]
oxygengine-core = { version = "0.27", path = "../core" }
navmesh = "0.12"
serde = { version = "1", features = ["derive"] }
bincode = "1"
