[package]
name = "oxygengine-script-web"
version = "0.5.3"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2018"
description = "Web scripting module for Oxygen Engine"
license-file = "../LICENSE"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-script-web"
readme = "../README.md"

[dependencies]
oxygengine-core = { version = "0.5", path = "../oxygengine-core" }
wasm-bindgen = "0.2"
js-sys = "0.3"
lazy_static = "1.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
