[package]
name = "oxygengine-script-web"
version = "0.11.2"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2018"
description = "Web scripting module for Oxygen Engine"
license-file = "../LICENSE"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-script-web"
readme = "../README.md"

[features]
default = ["web"]
composite-renderer = ["oxygengine-composite-renderer", "oxygengine-composite-renderer-backend-web"]
audio = ["oxygengine-audio"]
input = ["oxygengine-input"]
web = [
  "oxygengine-core/web",
  "oxygengine-composite-renderer/web",
  "oxygengine-composite-renderer-backend-web/web",
  "oxygengine-audio/web",
  "oxygengine-input/web",
]
scalar64 = [
  "oxygengine-core/scalar64",
  "oxygengine-utils/scalar64",
  "oxygengine-composite-renderer/scalar64",
  "oxygengine-composite-renderer-backend-web/scalar64",
  "oxygengine-audio/scalar64",
  "oxygengine-input/scalar64",
]

[dependencies]
oxygengine-core = { version = "0.11", path = "../oxygengine-core" }
oxygengine-utils = { version = "0.11", path = "../oxygengine-utils" }
wasm-bindgen = "0.2"
js-sys = "0.3"
lazy_static = "1.4"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
num = "0.2"

[dependencies.oxygengine-composite-renderer]
version = "0.11"
path = "../oxygengine-composite-renderer"
optional = true

[dependencies.oxygengine-composite-renderer-backend-web]
version = "0.11"
path = "../oxygengine-composite-renderer-backend-web"
optional = true

[dependencies.oxygengine-audio]
version = "0.11"
path = "../oxygengine-audio"
optional = true

[dependencies.oxygengine-input]
version = "0.11"
path = "../oxygengine-input"
optional = true
