[package]
name = "oxygengine-script-web"
version = "0.5.5"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2018"
description = "Web scripting module for Oxygen Engine"
license-file = "../LICENSE"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-script-web"
readme = "../README.md"

[dependencies]
oxygengine-core = { version = "0.5", path = "../oxygengine-core" }
oxygengine-utils = { version = "0.5", path = "../oxygengine-utils" }
wasm-bindgen = "0.2"
js-sys = "0.3"
lazy_static = "1.3"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
num = "0.2"

[dependencies.oxygengine-composite-renderer]
version = "0.5"
path = "../oxygengine-composite-renderer"
optional = true

[dependencies.oxygengine-composite-renderer-backend-web]
version = "0.5"
path = "../oxygengine-composite-renderer-backend-web"
optional = true

[dependencies.oxygengine-audio]
version = "0.5"
path = "../oxygengine-audio"
optional = true

[dependencies.oxygengine-input]
version = "0.5"
path = "../oxygengine-input"
optional = true

[features]
composite-renderer = ["oxygengine-composite-renderer", "oxygengine-composite-renderer-backend-web"]
audio = ["oxygengine-audio"]
input = ["oxygengine-input"]
