[package]
name = "oxygengine-utils"
version = "0.19.1"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2018"
description = "Utilities module for Oxygen Engine"
license-file = "../LICENSE"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-utils"
readme = "../README.md"

[features]
parallel = ["rayon"]
scalar64 = []

[dependencies]
serde = { version = "1", features = ["derive"] }
noise = { version = "0.6", default-features = false }
rayon = { version = "1.3", optional = true }
