[package]
name = "oxygengine-utils"
version = "0.3.12"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2018"
description = "Utilities module for Oxygen Engine"
license = "MIT"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-utils"
readme = "../README.md"

[features]
parallel = ["rayon"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
noise = { version = "0.5", default-features = false }
rayon = { version = "1.0", optional = true }
