[package]
name = "oxygengine-overworld"
version = "0.26.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "RPG overworld module for Oxygengine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-overworld"
readme = "../../README.md"

[features]
web = [
  "oxygengine-core/web",
  "oxygengine-navigation/web",
]
parallel = [
  "oxygengine-core/parallel",
  "oxygengine-navigation/parallel",
]
scalar64 = [
  "oxygengine-core/scalar64",
  "oxygengine-navigation/scalar64",
]

[dependencies]
oxygengine-core = { version = "0.26", path = "../core" }
oxygengine-navigation = { version = "0.26", path = "../navigation" }
serde = { version = "1", features = ["derive"] }
