[package]
name = "oxygengine-visual-novel"
version = "0.14.1"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2018"
description = "Visual Novel module for Oxygen Engine"
license-file = "../LICENSE"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-visual-novel"
readme = "../README.md"

[features]
script-flow = ["oxygengine-script-flow"]
web = [
  "oxygengine-core/web",
  "oxygengine-animation/web",
  "oxygengine-script-flow/web",
]
parallel = [
  "oxygengine-core/parallel",
  "oxygengine-animation/parallel",
  "oxygengine-script-flow/parallel",
]
scalar64 = [
  "oxygengine-core/scalar64",
  "oxygengine-animation/scalar64",
  "oxygengine-script-flow/scalar64",
]

[dependencies]
oxygengine-core = { version = "0.14", path = "../oxygengine-core" }
oxygengine-animation = { version = "0.14", path = "../oxygengine-animation" }
serde = { version = "1", features = ["derive"] }

[dependencies.oxygengine-script-flow]
version = "0.14"
path = "../oxygengine-script-flow"
optional = true
