[package]
name = "oxygengine-visual-novel"
version = "0.43.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "Visual Novel module for Oxygengine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-visual-novel"
readme = "../../README.md"

[features]
web = [
  "oxygengine-core/web",
  "oxygengine-animation/web",
]
parallel = [
  "oxygengine-core/parallel",
  "oxygengine-animation/parallel",
]
scalar64 = [
  "oxygengine-core/scalar64",
  "oxygengine-animation/scalar64",
]

[dependencies]
oxygengine-core = { version = "0.43", path = "../core" }
oxygengine-animation = { version = "0.43", path = "../animation" }
serde = { version = "1", features = ["derive"] }
