[package]
name = "oxygengine-ai"
version = "0.46.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "AI module for Oxygengine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-ai"
readme = "../../README.md"

[features]
web = ["oxygengine-core/web"]
parallel = ["oxygengine-core/parallel"]
scalar64 = ["oxygengine-core/scalar64", "emergent/scalar64"]

[dependencies]
oxygengine-core = { version = "0.46", path = "../core" }
emergent = "1.5"
serde = { version = "1", features = ["derive"] }
