[package]
name = "oxygengine-composite-renderer"
version = "0.3.10"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2018"
description = "Composite renderer module for Oxygen Engine"
license = "MIT"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-composite-renderer"
readme = "../README.md"

[dependencies]
oxygengine-core = { version = "0.3", path = "../oxygengine-core" }
png = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
