[package]
name = "oxygengine-audio-backend-web"
version = "0.44.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "Audio Web backend module for Oxygengine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-audio-backend-web"
readme = "../../README.md"

[features]
scalar64 = ["oxygengine-core/scalar64", "oxygengine-audio/scalar64"]

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
futures = "0.3"

[dependencies.oxygengine-core]
version = "0.44"
path = "../core"
features = ["web"]

[dependencies.oxygengine-backend-web]
version = "0.44"
path = "../backend-web"

[dependencies.oxygengine-audio]
version = "0.44"
path = "../audio"
features = ["web"]

[dependencies.web-sys]
version = "0.3"
features = [
  "AudioContext",
  "AudioContextState",
  "AudioBuffer",
  "AudioBufferSourceNode",
  "AudioParam",
  "AudioDestinationNode",
  "AudioNode",
  "GainNode",
  "HtmlAudioElement",
  "HtmlMediaElement",
  "MediaElementAudioSourceNode",
  "Blob",
  "Url",
]
