[package]
name = "oxygengine-chat-server"
version = "0.5.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2018"
description = "Oxygengine Chat Demo"
license = "MIT"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine"

[dependencies]
oxygengine = { version = "0.5", path = "../../..", features = ["desktop-headless-game"] }
bincode = "1.1"
