[package]
name = "oxygengine-chat-server"
version = "0.3.12"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2018"

[dependencies]
oxygengine = { version = "0.3", path = "../../..", features = ["desktop-headless-game"] }
bincode = "1.1"
