[package]
name = "oxygengine-core"
version = "0.30.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "Core module for Oxygengine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-core"
readme = "../../README.md"

[features]
web = ["typid/web"]
parallel = ["rayon"]
scalar64 = []

[dependencies]
oxygengine-ignite-types = { version = "0.30", path = "../ignite-types" }
oxygengine-ignite-derive = { version = "0.30", path = "../ignite-derive" }
typid = "1"
serde = { version = "1", features = ["derive"] }
serde-intermediate = "1.5"
bincode = "1"
serde_yaml = "=0.8.26"
rayon = { version = "1.3", optional = true }
hecs = { version = "0.9", features = ["macros"] }
lazy_static = "1.4"
pest = "2.1"
pest_derive = "2.1"
