[package]
name = "oxygengine-composite-renderer-backend-web"
version = "0.26.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "Composite renderer Web backend module for Oxygengine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-composite-renderer-backend-web"
readme = "../../README.md"

[features]
scalar64 = ["oxygengine-core/scalar64", "oxygengine-composite-renderer/scalar64"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"

[dependencies.oxygengine-core]
version = "0.26"
path = "../core"
features = ["web"]

[dependencies.oxygengine-composite-renderer]
version = "0.26"
path = "../composite-renderer"
features = ["web"]

[dependencies.web-sys]
version = "0.3"
features = [
  "CanvasRenderingContext2d",
  "Document",
  "Element",
  "HtmlCanvasElement",
  "HtmlImageElement",
  "Window",
  "Blob",
  "BlobPropertyBag",
  "Url",
  "FontFace",
  "FontFaceDescriptors",
  "FontFaceSet",
  "Event",
]
