[package]
name = "oxygengine-input-device-web"
version = "0.27.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "Web input devices module for Oxygengine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-input-device-web"
readme = "../../README.md"

[features]
scalar64 = ["oxygengine-core/scalar64", "oxygengine-input/scalar64"]

[dependencies]
wasm-bindgen = "0.2"

[dependencies.oxygengine-core]
version = "0.27"
path = "../core"
features = ["web"]

[dependencies.oxygengine-input]
version = "0.27"
path = "../input"
features = ["web"]

[dependencies.web-sys]
version = "0.3"
features = [
  "Document",
  "Element",
  "Window",
  "MouseEvent",
  "KeyboardEvent",
  "TouchEvent",
  "TouchList",
  "Touch",
  "EventTarget",
]
