[package]
name = "oxygengine-ignite"
version = "0.4.4"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2018"
description = "CLI app used to setup new Oxygen Engine project"
license-file = "../LICENSE"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-ignite"
readme = "../README.md"

[dependencies]
clap = "2.33"
cargo_metadata = "0.8"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
