[package]
name = "oxygengine-ha-renderer-debugger"
version = "0.40.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "Debugger for Hardware Accelerated renderer module for Oxygengine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-ha-renderer"
readme = "../../README.md"

[features]
web = ["oxygengine-core/web"]
parallel = ["oxygengine-core/parallel"]
scalar64 = ["oxygengine-core/scalar64"]

[dependencies]
oxygengine-core = { version = "0.40", path = "../core" }
oxygengine-ha-renderer = { version = "0.40", path = "../ha-renderer" }
oxygengine-editor-tools = { version = "0.40", path = "../editor-tools" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
