[package]
name = "oxygengine-physics-2d"
version = "0.42.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "2D physics module for Oxygengine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-physics-2d"
readme = "../../README.md"

[features]
web = ["oxygengine-core/web"]
parallel = ["oxygengine-core/parallel"]
scalar64 = ["oxygengine-core/scalar64"]

[dependencies]
oxygengine-core = { version = "0.42", path = "../core" }
serde = { version = "1", features = ["derive"] }

[dependencies.ncollide2d]
version = "=0.32"
default-features = false
features = ["dim2", "serde-serialize"]

[dependencies.nphysics2d]
version = "0.24"
default-features = false
features = ["dim2", "use-wasm-bindgen"]
