[package]
name = "oxygengine-integration-ow-ha"
version = "0.22.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "Integration module of RPG overworld and Hardware Accelerated rendering for Oxygengine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-integration-ow-ha"
readme = "../../README.md"

[features]
web = [
  "oxygengine-core/web",
  "oxygengine-overworld/web",
  "oxygengine-ha-renderer/web",
]
parallel = [
  "oxygengine-core/parallel",
  "oxygengine-overworld/parallel",
  "oxygengine-ha-renderer/parallel",
]
scalar64 = [
  "oxygengine-core/scalar64",
  "oxygengine-overworld/scalar64",
  "oxygengine-ha-renderer/scalar64",
]

[dependencies]
oxygengine-core = { version = "0.22", path = "../core" }
oxygengine-overworld = { version = "0.22", path = "../overworld" }
oxygengine-ha-renderer = { version = "0.22", path = "../ha-renderer" }
serde = { version = "1", features = ["derive"] }
