[triggers.mouse]
mouse-action = "left"

[axes.mouse]
mouse-x = "x"
mouse-y = "y"

[triggers.touch]
touch-action = "touch"

[axes.touch]
touch-x = "x"
touch-y = "y"

[triggers.keyboard]
space = "Space"
enter = "Enter"

[axes.keyboard]
w = "KeyW"
s = "KeyS"
a = "KeyA"
d = "KeyD"
up = "ArrowUp"
down = "ArrowDown"
left = "ArrowLeft"
right = "ArrowRight"
