[package]
name = "prototype"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "prototype"
path = "../../src/desktop_main.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
rand = "0.8"

[dependencies.oxygengine]
version = "0.44"
features = ["desktop-ha-prototype"]
