[package]
name = "oxygengine-ha-renderer-tools"
version = "0.45.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "Tools for Hardware Accelerated renderer module for Oxygengine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-ha-renderer-tools"
readme = "../../README.md"

[dependencies]
oxygengine-build-tools = { version = "0.45", path = "../build-tools" }
oxygengine-core = { version = "0.45", path = "../core" }
oxygengine-ha-renderer = { version = "0.45", path = "../ha-renderer" }
oxygengine-animation = { version = "0.45", path = "../animation" }
serde = { version = "1", features = ["derive"] }
serde-xml-rs = "0.6"
serde_json = "1"
image = "0.24"
texture_packer = "0.25"
ldtk_rust = "0.6"
chrobry-core = "1"

[[bin]]
name = "oxygengine-ha-renderer-atlas"
path = "./src/atlas_tool.rs"

[[bin]]
name = "oxygengine-ha-renderer-bmfont"
path = "./src/bmfont_tool.rs"

[[bin]]
name = "oxygengine-ha-renderer-sdf"
path = "./src/sdf_tool.rs"

[[bin]]
name = "oxygengine-ha-renderer-ldtk"
path = "./src/ldtk_tool.rs"

[[bin]]
name = "oxygengine-ha-renderer-spine"
path = "./src/spine/main.rs"
