[package]
name = "oxygengine-ha-renderer-tools"
version = "0.22.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "Tools for Hardware Accelerated renderer module for Oxygengine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-ha-renderer-tools"
readme = "../../README.md"

[dependencies]
oxygengine-build-tools = { version = "0.22", path = "../build-tools" }
oxygengine-core = { version = "0.22", path = "../core" }
oxygengine-ha-renderer = { version = "0.22", path = "../ha-renderer" }
serde = { version = "1", features = ["derive"] }
serde-xml-rs = "0.5"
serde_yaml = "0.8"
serde_json = "1"
image = "0.23"
texture_packer = "0.23"
ldtk_rust = "0.5"
chrobry-core = "1"

[[bin]]
name = "oxygengine-ha-renderer-atlas"
path = "./src/atlas_tool.rs"

[[bin]]
name = "oxygengine-ha-renderer-bmfont"
path = "./src/bmfont_tool.rs"

[[bin]]
name = "oxygengine-ha-renderer-sdf"
path = "./src/sdf_tool.rs"

[[bin]]
name = "oxygengine-ha-renderer-ldtk"
path = "./src/ldtk_tool.rs"
