[package]
name = "oxygengine-pws"
version = "0.28.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "Oxygengine procedural world simulation"
license = "MIT"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-pws"

[dependencies]
minifb = "0.19"
rand = "0.8"

[dependencies.oxygengine-procedural]
version = "0.28"
path = "../../engine/procedural"
features = ["parallel"]
