[package]
name = "oxygengine-pws"
version = "0.3.10"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2018"
description = "Oxygen Engine procedural world simulation"
license = "MIT"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine"

[dependencies]
minifb = "0.11"
oxygengine-procedural = { version = "0.3", path = "../../oxygengine-procedural" }
rand = "0.6"
