[package]
name = "oxygengine-utils"
version = "0.46.1"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "Utilities module for Oxygengine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-utils"
readme = "../../README.md"

[features]
parallel = ["rayon"]
scalar64 = []

[dependencies]
serde = { version = "1", features = ["derive"] }
noise = { version = "0.8", default-features = false }
rayon = { version = "1.3", optional = true }
