[package]
name = "oxygengine-core"
version = "0.3.17"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2018"
description = "Core module for Oxygen Engine"
license-file = "../LICENSE"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-core"
readme = "../README.md"

[features]
web = ["uuid/wasm-bindgen"]
parallel = ["rayon", "specs/parallel", "specs-hierarchy/parallel"]

[dependencies]
uuid = { version = "0.7", features = ["serde", "v4"] }
serde = { version = "1.0", features = ["derive"] }
rayon = { version = "1.0", optional = true }
specs = { version = "0.14", default-features = false }
specs-hierarchy = { version = "0.3", default-features = false }
lazy_static = "1.3"
