[package]
name = "oxygengine-network-backend-web"
version = "0.28.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "Network Web backend module for Oxygengine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-network-backend-web"
readme = "../../README.md"

[features]
scalar64 = ["oxygengine-core/scalar64", "oxygengine-network/scalar64"]

[dependencies]
wasm-bindgen = "0.2"
byteorder = "1.3"
js-sys = "0.3"

[dependencies.oxygengine-core]
version = "0.28"
path = "../core"
features = ["web"]

[dependencies.oxygengine-network]
version = "0.28"
path = "../network"
features = ["web"]

[dependencies.web-sys]
version = "0.3"
features = [
  "Window",
  "WebSocket",
  "BinaryType",
  "Event",
  "MessageEvent",
]
