[package]
name = "rig-testbed"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "rig-testbed"
path = "../../src/desktop_main.rs"

[features]
distribution = []

[dependencies]
serde = { version = "1", features = ["derive"] }

[dependencies.oxygengine]
version = "0.42"
features = ["desktop-ha-game"]
