[package]
name = "oxygengine"
version = "0.24.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "Oxygengine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine"
readme = "../../README.md"

[features]
web-composite-game = [
  "oxygengine-ai",
  "oxygengine-animation",
  "oxygengine-audio",
  "oxygengine-audio-backend-web",
  "oxygengine-backend-web",
  "oxygengine-composite-renderer",
  "oxygengine-composite-renderer-backend-web",
  "oxygengine-core/web",
  "oxygengine-input",
  "oxygengine-input-device-web",
  "oxygengine-integration-p2d-cr",
  "oxygengine-integration-ui-cr",
  "oxygengine-navigation",
  "oxygengine-network",
  "oxygengine-network-backend-web",
  "oxygengine-physics-2d",
  "oxygengine-user-interface",
]
web-composite-visual-novel-game = [
  "oxygengine-ai",
  "oxygengine-animation",
  "oxygengine-audio",
  "oxygengine-audio-backend-web",
  "oxygengine-backend-web",
  "oxygengine-composite-renderer",
  "oxygengine-composite-renderer-backend-web",
  "oxygengine-core/web",
  "oxygengine-input",
  "oxygengine-input-device-web",
  "oxygengine-integration-p2d-cr",
  "oxygengine-integration-ui-cr",
  "oxygengine-integration-vn-ui",
  "oxygengine-user-interface",
  "oxygengine-visual-novel",
]
web-ha-game = [
  "oxygengine-ai",
  "oxygengine-animation",
  "oxygengine-audio",
  "oxygengine-audio-backend-web",
  "oxygengine-backend-web",
  "oxygengine-core/web",
  "oxygengine-ha-renderer/web",
  "oxygengine-input",
  "oxygengine-input-device-web",
  # "oxygengine-integration-p2d-ha",
  "oxygengine-integration-ui-ha",
  "oxygengine-navigation",
  "oxygengine-network",
  "oxygengine-network-backend-web",
  # "oxygengine-physics-2d",
  "oxygengine-user-interface",
]
desktop-headless-game = [
  "oxygengine-core/parallel",
  "oxygengine-ai",
  "oxygengine-navigation",
  "oxygengine-network",
  "oxygengine-network-backend-desktop",
]
desktop-native-headless-game = [
  "oxygengine-core/parallel",
  "oxygengine-ai",
  "oxygengine-navigation",
  "oxygengine-network",
  "oxygengine-network-backend-native",
]

[dependencies]
oxygengine-core = { version = "0.24", path = "../core" }
oxygengine-utils = { version = "0.24", path = "../utils" }

[dependencies.oxygengine-backend-web]
version = "0.24"
path = "../backend-web"
optional = true

[dependencies.oxygengine-input]
version = "0.24"
path = "../input"
optional = true

[dependencies.oxygengine-input-device-web]
version = "0.24"
path = "../input-device-web"
optional = true

[dependencies.oxygengine-composite-renderer]
version = "0.24"
path = "../composite-renderer"
optional = true

[dependencies.oxygengine-composite-renderer-backend-web]
version = "0.24"
path = "../composite-renderer-backend-web"
optional = true

[dependencies.oxygengine-network]
version = "0.24"
path = "../network"
optional = true

[dependencies.oxygengine-network-backend-web]
version = "0.24"
path = "../network-backend-web"
optional = true

[dependencies.oxygengine-network-backend-desktop]
version = "0.24"
path = "../network-backend-desktop"
optional = true

[dependencies.oxygengine-network-backend-native]
version = "0.24"
path = "../network-backend-native"
optional = true

[dependencies.oxygengine-procedural]
version = "0.24"
path = "../procedural"
optional = true

[dependencies.oxygengine-navigation]
version = "0.24"
path = "../navigation"
optional = true

[dependencies.oxygengine-audio]
version = "0.24"
path = "../audio"
optional = true

[dependencies.oxygengine-audio-backend-web]
version = "0.24"
path = "../audio-backend-web"
optional = true

[dependencies.oxygengine-physics-2d]
version = "0.24"
path = "../physics-2d"
optional = true

[dependencies.oxygengine-integration-ow-ha]
version = "0.24"
path = "../integration-ow-ha"
optional = true

[dependencies.oxygengine-integration-p2d-cr]
version = "0.24"
path = "../integration-p2d-cr"
optional = true

[dependencies.oxygengine-integration-ui-cr]
version = "0.24"
path = "../integration-ui-cr"
optional = true

[dependencies.oxygengine-integration-ui-ha]
version = "0.24"
path = "../integration-ui-ha"
optional = true

[dependencies.oxygengine-integration-vn-ui]
version = "0.24"
path = "../integration-vn-ui"
optional = true

[dependencies.oxygengine-script-flow]
version = "0.24"
path = "../script-flow"
optional = true

[dependencies.oxygengine-visual-novel]
version = "0.24"
path = "../visual-novel"
optional = true

[dependencies.oxygengine-ai]
version = "0.24"
path = "../ai"
optional = true

[dependencies.oxygengine-animation]
version = "0.24"
path = "../animation"
optional = true

[dependencies.oxygengine-user-interface]
version = "0.24"
path = "../user-interface"
optional = true

[dependencies.oxygengine-editor-tools]
version = "0.24"
path = "../editor-tools"
optional = true

[dependencies.oxygengine-ha-renderer]
version = "0.24"
path = "../ha-renderer"
optional = true

[dependencies.oxygengine-overworld]
version = "0.24"
path = "../overworld"
optional = true
