name: Rust

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Install Just
        run: cargo install just
      - name: Build
        run: just build
      # - name: Test
      #   run: just test
      - name: Install tools
        run: just install-tools
      - name: Clean project for the test
        if: github.ref == 'refs/heads/master'
        run: rm -rf ./* && ls -al
      - name: Create project with Ignite CLI
        if: github.ref == 'refs/heads/master'
        run: OXY_UPDATE_PRESETS=1 oxygengine-ignite new test
      - name: Build test project
        if: github.ref == 'refs/heads/master'
        run: cd test && ls -al && just prod package debug
