name: Rust

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --manifest-path ./engine/Cargo.toml --verbose
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --manifest-path ./engine/Cargo.toml --verbose
      - name: Install Ignite CLI
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --path ./engine/ignite --force
      - name: Install Composite Renderer tools
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --path ./engine/composite-renderer-tools --force
      - name: Install HA Renderer tools
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --path ./engine/ha-renderer-tools --force
      - name: Clean project for the test
        run: rm -rf ./* && ls -al
      - name: Create project with Ignite CLI
        run: OXY_UPDATE_PRESETS=1 oxygengine-ignite new test
      - name: Build test project
        run: cd test && ls -al && cat Cargo.toml && oxygengine-ignite package
