name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --all --verbose
    - name: Run tests
      run: cargo test --all --verbose
    - name: Install Ignite CLI
      run: cargo install --path oxygengine-ignite --forced
    - name: Create project with Ignite CLI
      run: oxygengine-ignite new test -d demos
