[package]
name = "oxygengine-prototype"
version = "0.40.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "Prototyping utilities module for Oxygengine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-procedural"
readme = "../../README.md"

[features]
web = [
  "oxygengine-core/web",
  "oxygengine-backend-web",
  "oxygengine-ha-renderer/web",
  "oxygengine-audio/web",
  "oxygengine-audio-backend-web",
  "oxygengine-input/web",
  "oxygengine-input-device-web",
]
parallel = [
  "oxygengine-core/parallel",
  "oxygengine-ha-renderer/parallel",
  "oxygengine-audio/parallel",
  "oxygengine-input/parallel",
]
scalar64 = [
  "oxygengine-core/scalar64",
  "oxygengine-backend-web/scalar64",
  "oxygengine-ha-renderer/scalar64",
  "oxygengine-audio/scalar64",
  "oxygengine-audio-backend-web/scalar64",
  "oxygengine-input/scalar64",
  "oxygengine-input-device-web/scalar64",
]

[dependencies]
oxygengine-core = { version = "0.40", path = "../core" }
oxygengine-backend-web = { version = "0.40", path = "../backend-web", optional = true }
oxygengine-audio = { version = "0.40", path = "../audio" }
oxygengine-audio-backend-web = { version = "0.40", path = "../audio-backend-web", optional = true }
oxygengine-input = { version = "0.40", path = "../input" }
oxygengine-input-device-web = { version = "0.40", path = "../input-device-web", optional = true }
oxygengine-ha-renderer = { version = "0.40", path = "../ha-renderer" }
oxygengine-editor-tools-backend-web = { version = "0.40", path = "../editor-tools-backend-web" }
oxygengine-ha-renderer-debugger = { version = "0.40", path = "../ha-renderer-debugger" }
serde = { version = "1", features = ["derive"] }
