[package]
name = "oxygengine-prototype"
version = "0.45.1"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2021"
description = "Prototyping utilities module for Oxygengine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/oxygengine"
repository = "https://github.com/PsichiX/oxygengine"
documentation = "https://docs.rs/oxygengine-procedural"
readme = "../../README.md"

[features]
web = [
  "oxygengine-core/web",
  "oxygengine-backend-web",
  "oxygengine-ha-renderer/web",
  "oxygengine-audio/web",
  "oxygengine-audio-backend-web",
  "oxygengine-input/web",
  "oxygengine-input-device-web",
  "oxygengine-editor-tools-backend-web",
  "oxygengine-ha-renderer-debugger",
]
desktop = [
  "oxygengine-backend-desktop",
  "oxygengine-ha-renderer/desktop",
  # "oxygengine-audio-backend-desktop",
  "oxygengine-input-device-desktop",
]
parallel = [
  "oxygengine-core/parallel",
  "oxygengine-ha-renderer/parallel",
  "oxygengine-audio/parallel",
  "oxygengine-input/parallel",
  "oxygengine-nodes/parallel",
]
scalar64 = [
  "oxygengine-core/scalar64",
  "oxygengine-backend-web/scalar64",
  "oxygengine-ha-renderer/scalar64",
  "oxygengine-audio/scalar64",
  "oxygengine-audio-backend-web/scalar64",
  "oxygengine-input/scalar64",
  "oxygengine-input-device-web/scalar64",
  "oxygengine-nodes/scalar64",
]

[dependencies]
oxygengine-core = { version = "0.45", path = "../core" }
oxygengine-backend-web = { version = "0.45", path = "../backend-web", optional = true }
oxygengine-backend-desktop = { version = "0.45", path = "../backend-desktop", optional = true }
oxygengine-audio = { version = "0.45", path = "../audio" }
oxygengine-audio-backend-web = { version = "0.45", path = "../audio-backend-web", optional = true }
# oxygengine-audio-backend-desktop = { version = "0.45", path = "../audio-backend-desktop", optional = true }
oxygengine-input = { version = "0.45", path = "../input" }
oxygengine-input-device-web = { version = "0.45", path = "../input-device-web", optional = true }
oxygengine-input-device-desktop = { version = "0.45", path = "../input-device-desktop", optional = true }
oxygengine-ha-renderer = { version = "0.45", path = "../ha-renderer" }
oxygengine-editor-tools-backend-web = { version = "0.45", path = "../editor-tools-backend-web", optional = true }
oxygengine-ha-renderer-debugger = { version = "0.45", path = "../ha-renderer-debugger", optional = true }
oxygengine-nodes = { version = "0.45", path = "../nodes" }
serde = { version = "1", features = ["derive"] }
rstar = "0.11"
